<script setup>
import { onMounted, ref } from 'vue'
import NoticeMessage from '../components/NoticeMessage.vue'
import { request } from '../api'
const students = ref([]); const courses = ref([]); const selectedCourse = ref(''); const roster = ref([]); const form = ref({ studentId: '', courseId: '' }); const loading = ref(false); const error = ref(''); const message = ref('')
async function loadOptions() { loading.value = true; error.value = ''; try { const [studentResult, courseResult] = await Promise.all([request('/students'), request('/courses')]); students.value = studentResult; courses.value = courseResult } catch (requestError) { error.value = requestError.message } finally { loading.value = false } }
async function enroll() { error.value = ''; message.value = ''; if (!form.value.studentId || !form.value.courseId) { error.value = 'Select both a student and a course.'; return }; try { const result = await request('/enrollments', { method: 'POST', body: JSON.stringify(form.value) }); message.value = result.message || 'Student enrolled successfully.'; form.value.studentId = ''; await showRoster() } catch (requestError) { error.value = requestError.message } }
async function showRoster() { if (!selectedCourse.value) { roster.value = []; return }; try { roster.value = await request(`/courses/${encodeURIComponent(selectedCourse.value)}/students`) } catch (requestError) { error.value = requestError.message } }
onMounted(loadOptions)
</script>
<template>
  <section class="page-heading"><div><p class="eyebrow">Relationships</p><h1>Enrollments</h1><p class="lede">Connect students to courses and review each course roster.</p></div></section>
  <section class="panel enrollment-panel"><div class="panel-heading"><div><p class="eyebrow">New enrollment</p><h2>Enroll a student</h2></div></div><form class="enrollment-form" @submit.prevent="enroll"><div class="field"><label for="enrollment-student">Student</label><select id="enrollment-student" v-model="form.studentId" required><option value="">Choose a student</option><option v-for="student in students" :key="student.id" :value="student.id">{{ student.name }} ({{ student.id }})</option></select></div><div class="field"><label for="enrollment-course">Course</label><select id="enrollment-course" v-model="form.courseId" required><option value="">Choose a course</option><option v-for="course in courses" :key="course.id" :value="course.id">{{ course.id }} - {{ course.name }}</option></select></div><button class="button button--primary" type="submit" :disabled="loading">Enroll student</button></form><NoticeMessage kind="error" :text="error" /><NoticeMessage kind="success" :text="message" /></section>
  <section class="panel enrollment-panel"><div class="panel-heading"><div><p class="eyebrow">Roster</p><h2>Students in a course</h2></div></div><div class="field"><label for="roster-course">Course</label><select id="roster-course" v-model="selectedCourse" @change="showRoster"><option value="">Choose a course</option><option v-for="course in courses" :key="course.id" :value="course.id">{{ course.id }} - {{ course.name }}</option></select></div><p v-if="!selectedCourse" class="empty-state">Choose a course to view its enrolled students.</p><p v-else-if="!roster.length" class="empty-state">No students are enrolled in this course.</p><ul v-else class="record-list"><li v-for="student in roster" :key="student.id"><div><strong>{{ student.name }}</strong><span>{{ student.id }}</span></div></li></ul></section>
</template>
